name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome
        - run: echo "My first github actions"

        - name: list all the files
        - run: ls -la

        - name: read the file
        - run: cat README.md

